---
spring:
  config:
    activate:
      on-profile: local
jwt:
  secret-key: ${JWT_KEY}
  refresh-expiration-time: ${REFRESH_EXPIRATION_TIME}
  access-expiration-time: ${ACCESS_EXPIRATION_TIME}
---
spring:
  config:
    activate:
      on-profile: dev

jwt:
  secret-key: ${JWT_KEY}
  refresh-expiration-time: ${REFRESH_EXPIRATION_TIME}
  access-expiration-time: ${ACCESS_EXPIRATION_TIME}